### ISSUE TITLE
README in English

### ISSUE THREAD

**Issue by Zaid-maker** [simon-valerio-epfl/notes-ba1-simon#1]
Love to see README in English

**Comment by Androz2091** [comment]
Hey! Are you at least an EPFL student? :joy: 
I can translate the README but I'm not sure it's useful as the first year at EPFL is completely in French x)

**Comment by Zaid-maker** [comment]
> Hey! Are you at least an EPFL student? :joy: 
> I can translate the README but I'm not sure it's useful as the first year at EPFL is completely in French x)

I am not a student of EPFL but I found this in my feed and read the code and find it interested lol
